//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceOnlineDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssistanceOnlineContext : DbContext
    {
        public AssistanceOnlineContext()
            : base("name=AssistanceOnlineContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Key> Key { get; set; }
        public virtual DbSet<HtmlTemplate> HtmlTemplate { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Assistance> Assistance { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<SubscriptionAssistance> SubscriptionAssistance { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
    }
}
