//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceOnlineDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assistance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assistance()
        {
            this.SubscriptionAssistance = new HashSet<SubscriptionAssistance>();
        }
    
        public int idAssistance { get; set; }
        public int idCourse { get; set; }
        public bool active { get; set; }
        public System.DateTime creationDate { get; set; }
        public System.DateTime modificationDate { get; set; }
        public string token { get; set; }
        public Nullable<int> numberAssistance { get; set; }
    
        public virtual Courses Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionAssistance> SubscriptionAssistance { get; set; }
    }
}
