//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceOnlineDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlTemplate
    {
        public int idHtmlTemplate { get; set; }
        public string template { get; set; }
        public System.DateTime creationDate { get; set; }
        public System.DateTime modificationDate { get; set; }
        public bool active { get; set; }
    }
}
