//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceOnlineDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        public int idKey { get; set; }
        public string description { get; set; }
        public string value { get; set; }
        public int type { get; set; }
        public System.DateTime creationDate { get; set; }
        public System.DateTime modification { get; set; }
        public bool active { get; set; }
    }
}
